name: build-deploy

on: [push]

jobs:
  yarn-build:
    name: Build Yarn
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Installation
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g yarn
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy-docker-image:
    name: Deploying on docker-hub
    runs-on: ubuntu-latest
    needs: yarn-build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: dist
      - name: test path
        run: |
          ls
          ls dist
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: whyrl/sshportal-ui
          path: "."
          dockerfile: "docker/Dockerfile"
          add_git_labels: true
          tag_with_ref: true
